export default {
    products: [
        {
            id: 1,
            name: 'Slim Shirt',
            image: '/images/1.jpg',
            price: 60,
            brand: 'nike',
            rating: 4.5,
            reviewers: 10,
            description: '',
        },
        {
            id: 2,
            name: 'Slim Jacket',
            image: '/images/2.jpg',
            price: 70,
            brand: 'adidas',
            rating: 4.5,
            reviewers: 80,
            description: '',
        },
        {
            id: 3,
            name: 'Short Jeans',
            image: '/images/3.jpg',
            price: 50,
            brand: 'apolo',
            rating: 4.5,
            reviewers: 25,
            description: '',
        },
        {
            id: 4,
            name: 'Full Bag',
            image: '/images/4.jpg',
            price: 80,
            brand: 'flaraven',
            rating: 4.5,
            reviewers: 100,
            description: '',
        },
        {
            id: 5,
            name: 'Hardisk External',
            image: '/images/5.jpg',
            price: 100,
            brand: 'apple',
            rating: 5,
            reviewers: 100,
            description: '',
        },
    ]
};