export default {
    auths: {
        LOGIN_USER_REQUEST: 'LOGIN_USER_REQUEST',
        LOGIN_USER_SUCCESS: 'LOGIN_USER_SUCCESS',
        LOGIN_USER_FAILED: 'LOGIN_USER_FAILED',        
        REGISTER_USER_REQUEST: 'REGISTER_USER_REQUEST',
        REGISTER_USER_SUCCESS: 'REGISTER_USER_SUCCESS',
        REGISTER_USER_FAILED: 'REGISTER_USER_FAILED', 
    },

    products: {
        PRODUCT_LIST_REQUEST: 'PRODUCT_LIST_REQUEST',
        PRODUCT_LIST_SUCCESS: 'PRODUCT_LIST_SUCCESS',
        PRODUCT_LIST_FAILED: 'PRODUCT_LIST_FAILED',

        PRODUCT_DETAILS_REQUEST: 'PRODUCT_DETAILS_REQUEST',
        PRODUCT_DETAILS_SUCCESS: 'PRODUCT_DETAILS_SUCCESS',
        PRODUCT_DETAILS_ERROR: 'PRODUCT_DETAILS_ERROR'
    },

    carts: {
        CART_ADD_ITEM: 'CART_ADD_ITEM',
        CART_DELETE_ITEM: 'CART_DELETE_ITEM',
        CART_ERROR: 'CART_ERROR' 
    }
}