export default {
    products: {
        PRODUCT_LIST_REQUEST: 'PRODUCT_LIST_REQUEST',
        PRODUCT_LIST_SUCCESS: 'PRODUCT_LIST_SUCCESS',
        PRODUCT_LIST_FAILED: 'PRODUCT_LIST_FAILED',

        PRODUCT_DETAILS_REQUEST: 'PRODUCT_DETAILS_REQUEST',
        PRODUCT_DETAILS_SUCCESS: 'PRODUCT_DETAILS_SUCCESS',
        PRODUCT_DETAILS_ERROR: 'PRODUCT_DETAILS_ERROR'
    }
}