export default {
    products: {
        PRODUCT_LIST_REQUEST: 'PRODUCT_LIST_REQUEST',
        PRODUCT_LIST_SUCCESS: 'PRODUCT_LIST_SUCCESS',
        PRODUCT_LIST_FAILED: 'PRODUCT_LIST_FAILED',

        PRODUCT_DETAILS_REQUEST: 'PRODUCT_DETAILS_REQUEST',
        PRODUCT_DETAILS_SUCCESS: 'PRODUCT_DETAILS_SUCCESS',
        PRODUCT_DETAILS_ERROR: 'PRODUCT_DETAILS_ERROR'
    },

    carts: {
        CART_ADD_ITEM: 'CART_ADD_ITEM',
        CART_DELETE_ITEM: 'CART_DELETE_ITEM',
        CART_ERROR: 'CART_ERROR' 
    }
}